#!/usr/bin/env bash

# Remove Base16 Shell color scripts
if [[ -d "$HOME/.config/base16-shell" ]]; then
  rm -rf "$HOME/.config/base16-shell"
fi

# Remove base16 Theme
if [[ -L "$HOME/.base16_theme" ]]; then
  rm -rf "$HOME/.base16_theme"
fi

# Remove base16_background
if [[ -f "$HOME/.vimrc_background" ]]; then
  rm -rf "$HOME/.vimrc_background"
fi

# Remove Pure Prompt
if [[ -L "$HOME/.local/share/zsh/functions/prompt_pure_setup" ]]; then
  rm -rf  "$HOME/.local/share/zsh/functions/prompt_pure_setup"
fi

if [[ -L "$HOME/.local/share/zsh/functions/async" ]]; then
   rm -rf "$HOME/.local/share/zsh/functions/async"
fi

if [[ -d "$HOME/.config/pure" ]]; then
  rm -rf "$HOME/.config/pure"
fi

# Remove zsh-history-substring-search
if [[ -L "$HOME/.local/share/zsh/functions/zsh-history-substring-search" ]]; then
  rm -rf "$HOME/.local/share/zsh/functions/zsh-history-substring-search"
fi

if [[ -d "$HOME/.config/zsh-history-substring-search" ]]; then
  rm -rf "$HOME/.config/zsh-history-substring-search"
fi

# Remove zsh-syntax-highlighting
if [[ -L "$HOME/.local/share/zsh/functions/zsh-syntax-highlighting" ]]; then
  rm -rf "$HOME/.local/share/zsh/functions/zsh-syntax-highlighting"
fi

if [[ -d "$HOME/.config/zsh-syntax-highlighting" ]]; then
  rm -rf "$HOME/.config/zsh-syntax-highlighting"
fi

# Remove Tmux Plugins
if [[ -d "$HOME/.tmux" ]]; then
  rm -rf "$HOME/.tmux"
fi
