#!/usr/bin/env bash

# Grap Nova iTerm Theme
# https://trevordmiller.com/projects/nova
if [[ ! -f "$HOME/.iterm/themes/nova.itermcolors" ]]; then
  curl -fLo $HOME/.iterm/themes/nova.itermcolors --create-dirs \
    https://raw.githubusercontent.com/trevordmiller/nova-iterm/master/build/nova.itermcolors
fi

# Grab Pure Prompt
# https://github.com/sindresorhus/pure
if [[ ! -d "$HOME/.config/pure" ]]; then
  git clone https://github.com/sindresorhus/pure.git \
    "$HOME/.config/pure"

  # Based on convention, install the pure functions
  if [[ ! -d "$HOME/.local/share/zsh/functions" ]]; then
    mkdir -p "$HOME/.local/share/zsh/functions"
  fi

  if [[ ! -L "$HOME/.local/share/zsh/functions/prompt_pure_setup" ]]; then
    ln -s "$HOME/.config/pure/pure.zsh" "$HOME/.local/share/zsh/functions/prompt_pure_setup"
  fi

  if [[ ! -L "$HOME/.local/share/zsh/functions/async" ]]; then
    ln -s "$HOME/.config/pure/async.zsh" "$HOME/.local/share/zsh/functions/async"
  fi
fi

# Grab zsh-history-substring-search
# https://github.com/zsh-users/zsh-history-substring-search
if [[ ! -d "$HOME/.config/zsh-history-substring-search" ]]; then
  git clone git@github.com:zsh-users/zsh-history-substring-search.git \
    "$HOME/.config/zsh-history-substring-search"

  # Based on convention, install the zsh history substring search
  if [[ ! -d "$HOME/.local/share/zsh/functions" ]]; then
    mkdir -p "$HOME/.local/share/zsh/functions"
  fi

  if [[ ! -L "$HOME/.local/share/zsh/functions/zsh-history-substring-search" ]]; then
    ln -s "$HOME/.config/zsh-history-substring-search/zsh-history-substring-search.zsh" "$HOME/.local/share/zsh/functions/zsh-history-substring-search"
  fi
fi

# Grab zsh-syntax-highlighting
# https://github.com/zsh-users/zsh-syntax-highlighting
if [[ ! -d "$HOME/.config/zsh-syntax-highlighting" ]]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
    "$HOME/.config/zsh-syntax-highlighting"

  # Based on convention, install the zsh history substring search
  if [[ ! -d "$HOME/.local/share/zsh/functions" ]]; then
    mkdir -p "$HOME/.local/share/zsh/functions"
  fi

  if [[ ! -L "$HOME/.local/share/zsh/functions/zsh-syntax-highlighting" ]]; then
    ln -s "$HOME/.config/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" "$HOME/.local/share/zsh/functions/zsh-syntax-highlighting"
  fi
fi

# Grab Tmux Plugin Manager
if [[ ! -d "$HOME/.tmux/plugins/tpm" ]]; then
  git clone https://github.com/tmux-plugins/tpm.git \
    "$HOME/.tmux/plugins/tpm"
fi

# Grab Plug for managing vim plugins
# Needs to be in the autoload directory
if [[ ! -f "$HOME/.local/share/nvim/site/autoload/plug.vim" ]]; then
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
